CREATE USER IF NOT EXISTS 'user'@'127.0.0.1' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'127.0.0.1' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS test;
USE test;
DROP TABLE IF EXISTS t;
CREATE TABLE t (a INTEGER, b INTEGER);
INSERT INTO t VALUES (1, 2), (3, 4), (5, 6), (7, 8);
